


-- FUNCION
CREATE OR REPLACE FUNCTION SP_TELEFONO_CLIENTES_I() RETURNS TRIGGER
AS 
$$
	DECLARE
	tamanio_letra int:=CHAR_LENGTH(NEW.TELEFONOCLI);
	BEGIN
		IF (tamanio_letra<10 OR tamanio_letra>10) THEN
			RAISE NOTICE 'EL NUMERO INGRESADO ES INCORRECTO';
			ROLLBACK;
		ELSE
			RAISE NOTICE 'EL DATO INGRESADO ES CORRECTO';
			RETURN NEW;
		END IF;
	END
$$
LANGUAGE plpgsql;

-- TRIGGER
CREATE TRIGGER TR_TELEFONO_CLIENTE_I
BEFORE INSERT ON CLIENTES
FOR EACH ROW
EXECUTE PROCEDURE SP_TELEFONO_CLIENTES_I();

-- PRUEBA
INSERT INTO CLIENTES VALUES ('1003570817','Sylvana','Torres','storres@gmail.com','0959862753','Santa Rosa del Tejar');




